export const faqData = [
  {
    id: 1,
    title: `Is it possible to restore an account that i have been withdrawn? (탈퇴한 계정을 복구할 수 있나요?)`,
    content: `The withdrawn account will be permanently deleted and cannot be restored. (탈퇴하는 영구 삭제되며 복구 불가능합니다.)`,
    category: `account`,
  },
  {
    id: 2,
    title: `Where can I withdraw my membership? (회원탈퇴는 어디서 하나요?)`,
    content: `You can withdraw by clicking ‘here’ on the button of setting menu. (setting 메뉴 하단에 Please click here에 here 부분을 누르고 진행하시면 됩니다.)`,
    category: `account`,
  },
  {
    id: 3,
    title: `I don’t get a verification email. What should i do? (인증 메일이 오지 않아요. 어떻게 해야하나요?)`,
    content: `Please check below in case you have not received a confirmation email.(메일이 오지 않는 경우 아래 내용을 확인해주세요.)\n\nPlease make sure it is a valid email address. (유효한 이메일 주소인지 확인해 주세요.)\n\nPlease check if your XYLO account (noreply@xylo.io) has been spammed.(XYLO계정(noreply@xylo.io)이 스팸 처리되었는지 확인해 주세요.)\n\nPlease check the storage space of your inbox.(수신함의 저장 공간을 확인해 주세요.)`,
    category: `account`,
  },
  {
    id: 4,
    title: `How do I change my name, password and email? (이름, 비밀번호, 이메일을 어떻게 변경하나요?)`,
    content: `Updates pertaining to your account can be made from the Settings menu.(gear mark on the top right) (Setting(우측상단 톱니바퀴) 메뉴에서 각각 변경하실 수 있습니다.))`,
    category: `account`,
  },
  {
    id: 5,
    title: `I forgot my password. How can I find it? (비밀번호를 잊어버렸어요. 어떻게 찾을 수 있나요?)`,
    content: `A temporary password will be provided through the forgot password feature on the sign in page. (Sign In 페이지의 forgot password를 클릭해 임시 비밀번호를 발급받을 수 있습니다.)`,
    category: `account`,
  },
  {
    id: 6,
    title: `Where can I check my wallet address? (내 지갑 주소를 어디서 확인하나요?)`,
    content: `You can check the address on the Wallet page at the bottom. (하단의 Wallet 페이지에서 address를 확인할 수 있습니다.)`,
    category: `wallet`,
  },
  {
    id: 7,
    title: `Can I change the address of XYLO wallet? (XYLO지갑 주소를 바꿀 수 있나요?)`,
    content: `One wallet address is given per account and cannot be changed. (계정 당 하나의 지갑 주소가 부여되며 변경이 불가능합니다.)`,
    category: `wallet`,
  },
  {
    id: 8,
    title: `What is the community pool fund for? (커뮤니티풀 어디에 쓰이나요?)`,
    content: `It is used according to approved governance proposals such as new crypto project investments, network updates. (통과된 제안에 따라 사용됩니다. 일반적으로 신규 크립토 프로젝트 투자, 네트워크 업데이트 등 거버넌스 결정 방향에 사용됩니다.)`,
    category: `pool`,
  },
  {
    id: 9,
    title: `What is the difference between investment and staking? (투자와 스테이킹의 차이는 무엇인가요?)`,
    content: `XYLO acts as a Venture Capital (VC) and activates the mainnet and various projects through community pool investment. This gives you more rewards than staking, and increases the value of coins through platform expansion. (XYLO은 VC(Venture Capital) 역할을 하며 커뮤니티풀 투자를 통해 메인넷 및 다양한 프로젝트를 활성화합니다. 이를 통해 스테이킹보다 더 많은 보상을 받을 수 있으며, 플랫폼 확장을 통해 코인의 가치가 상승합니다.)`,
    category: `pool`,
  },
  {
    id: 10,
    title: `Where can I find out the details of my investment? (내가 투자한 내역은 어디서 확인하나요?)`,
    content: `You can check the remittance and deposit details through Transaction on the Wallet page. (Wallet 페이지의 Transaction에서 송금 및 입금 내역을 확인하실 수 있습니다.)`,
    category: `pool`,
  },
  {
    id: 11,
    title: `Where and How can I invest? (투자는 어디서, 어떻게 하나요?)`,
    content: `You can invest with the Send to Community pool button at the top of the Wallet page at the bottom of the app. (앱 하단 Wallet 페이지 상단의 Send to Community pool 버튼으로 투자가 가능합니다.)`,
    category: `pool`,
  },
  {
    id: 12,
    title: `Is it possible to delegate to other XOs during the delegation? (위임 중에 다른 SO에게도 위임할 수 있나요?)`,
    content: `XOP can be delegated to multiple XOs. If you have already delegated the XOP, you can make additional investments in Community Pool and then obtain and delegate the XOP. (XOP를 여러 XO에 위임할 수 있습니다. 이미 보유중인 XOP를 위임한 경우 커뮤니니풀에 추가 투자 후 XOP를 획득하여 위임할 수 있습니다.)`,
    category: `delegate`,
  },
  {
    id: 13,
    title: `Can't I cancel the delegation? (위임을 취소할 수 없나요?)`,
    content: `You can’t undelegate now. We will planning to support undelegate. ( 현재 위임 취소는 블가능하며, 추후 임의 취소가 가능하도록 지원 예정입니다.)`,
    category: `delegate`,
  },
  {
    id: 14,
    title: `Can XOP be traded on other exchanges? (XOP를 타 거래소에서 거래할 수 있나요?)`,
    content: `XOP is a delegate governance token and cannot on traded on other exchanges. It can only be obtained through community pool investment. (XOP는 위임 가능한 거버넌스 토큰이므로 다른 거래소에서 거래가 불가능합니다. 또한 커뮤니티풀 투자를 통해서만 획득할 수 있습니다.)`,
    category: `delegate`,
  },
  {
    id: 15,
    title: `Is it okey not to delegate XOP?(XOP를 위임하지 않아도 되나요?)`,
    content: `If you have XOP without delegation, you cannot receive reword. (위임 없이 XOP를 보유하면 보상을 받을 수 있습니다.)`,
    category: `delegate`,
  },
  {
    id: 16,
    title: `How can I use XOP(XOP는 어떻게 사용하나요?)`,
    content: `XOP acquired after investment will be delegated to XO. Please refer to Use XYLO for detailed delegation method. 투자 후 취득한 XOP는 XO에게 위임됩니다. 자세한 위임 방법은 Use XYLO을 참고하세요.)`,
    category: `delegate`,
  },
  {
    id: 17,
    title: `Can I delegate TOKEN? (TOKEN로 위임할 수 있나요?)`,
    content: `You can't delegate TOKEN immediately. If you invest TOKEN in a community pool, the same amount of XOP will be issued, which you can delegate. (TOKEN를 바로 위임할 수는 없습니다. 커뮤니티 풀에 TOKEN를 투자하면 동량의 XOP가 발급되는데, 이 XOP를 이용해 위임할 수 있습니다.)`,
    category: `delegate`,
  },
  {
    id: 18,
    title: `How do I delegate? (위임은 어떻게 하나요?)`,
    content: `If you select the XO you want to delegate from the XO page at the bottom of the app, you can delegate from the DELEGATE button on the detail page. (앱 하단 XO 페이지에서 위임할 XO를 선택하면 상세 페이지에서 Delegate 버튼으로 위임하실 수 있습니다.)`,
    category: `delegate`,
  },
  {
    id: 19,
    title: `What are the roles of XO? (XO의 역할은 무엇인가요?)`,
    content: `The XO plays various roles such as node operator, voter, and information provider. (XO는 노드 운영자, 투표자, 정보 제공자 등의 다양한 역할을 수행합니다.)`,
    category: `owner`,
  },
  {
    id: 20,
    title: `Do all XO need to operate node by themselves? (직접 노드를 운영해야 하나요?)`,
    content: `For the XO, node operation is mandatory, but direct operation is optional. (During an Open beta, for the safety and stability, only node consignment is operated.) (XO의 경우 노드 운영은 필수이지만 직접 운영하는 것은 선택 사항입니다. (현재는 오픈 베타 기간으로 안정된 서비스를 위해 위탁운영을 하고 있습니다.))`,
    category: `owner`,
  },
  {
    id: 21,
    title: `What are the criteria for selecting XO? (XO의 선택 기준은 무엇인가요?)`,
    content: `The delegate can select the XO to delegate by referring to the pledges, rankings, voting history, etc. on the XO personal page.(위임자는 XO 개인 페이지의 공약, 순위, 투표 히스토리 등을 참고하여 위임할 SO를 선택할 수 있습니다.)`,
    category: `owner`,
  },
  {
    id: 22,
    title: `How many XO can receive additional XO reward? (XO의 추가 보상은 몇 위까지 받을 수 있나요?)`,
    content: `Additional reward will be given as block reward from XO No. 1 to 6, and ranking reward from No. 1 to 12. (XO 1위부터 6위까지 블록보상, 1위부터 12위까지 순위보상으로 역할과 순위에 따른 추가 보상이 지급됩니다.)`,
    category: `owner`,
  },
  {
    id: 23,
    title: `What can the proposer suggest? (어떤 내용을 제안할 수 있나요?)`,
    content: `You can register proposals related to platform, network, token economy, investment use, etc. (플랫폼, 네트워크, 토큰 이코노미, 투자금의 사용 등과 관련된 제안을 등록할 수 있습니다.)`,
    category: `proposal`,
  },
  {
    id: 24,
    title: `Can anyone register a proposal? (누구나 제안을 등록할 수 있나요?)`,
    content: `Anyone can register proposals and a certain deposit is required to register. (A deposit amount can change depending on TOKEN price.) (누구나 제안 등록할 수 있으며, 등록을 위해서는 일정 보증금이 필요합니다. (보증금 책정 가격은 TOKEN 시세에 따라 변동될 수 있습니다.))`,
    category: `proposal`,
  },
  {
    id: 25,
    title: `If I delegate to two or more XO, do I have the right to vote as much as I delegated? (다수(2인 이상)의 XO에게 위임을 했을 경우 위임한 만큼 투표권이 생기나요?)`,
    content: `In principle, if you delegate 100 XOP or more to an XO, you will be given the right to vote in the XO voting. If you have delegated 100 SOP or more to multiple XO, you will be given the right to vote in each XO group. (원칙상 XO에게 100XOP 이상을 위임했을 경우 해당 XO 투표에서의 투표권이 부여되며 다수의 XO에게 각각 100XOP 이상의 자산을 위임을 했을 경우 해당하는 XO 수만큼의 투표권이 부여됩니다.)`,
    category: `vote`,
  },
  {
    id: 26,
    title: `Can I change or cancel my decision after I voted? (투표 후 투표 결과를 번복 또는 취소할 수 있나요?)`,
    content: `All users who voted cannot change or cancel the decision after exercising their voting rights. So, please vote carefully with this rule in mind. (투표권이 있는 모든 유저는 투표권을 행사 이후 번복 또는 취소할 수 없습니다. 따라서 신중하게 판단하셔서 투표 권리 행사하시기 바랍니다.)`,
    category: `vote`,
  },
  {
    id: 27,
    title: `Are all votes recorded on the blockchain? (모든 투표 내역은 블록체인에 기록이 되나요?)`,
    content: `All the transactions are recorded on the blockchain when voting starts, and the voting results are also recorded on the blockchain. However, to encourage the participation of XOM, the contents are not recorded on the blockchain during the vote, but only the final result is recorded through the administrator at the end of voting. (In order to record all voting details on the blockchain, voting transactions of members with voting rights need to pay transaction fees from their wallets, and only the results after voting are recorded) (투표 시작과 함께 블록체인에 기록되며, 투표 종료 결과 또한 블록체인에 기록됩니다. 단, XOM분들의 적극적인 참여 활성화를 위해 투표 진행 시에는 블록체인에 기록하지 않고 투표 종료 시 관리자를 통해 최종 결과 기록을 진행합니다. (블록체인에 모든 투표 내역을 기록하기 위해서는 투표권을 보유한 회원분들의 투표 트랜잭션을 본인의 월렛에서 트랜잭션 수수료 지불이 필요하여 투표 종료 시 결과만 기록합니다.))`,
    category: `vote`,
  },
  {
    id: 28,
    title: `What are the criteria for getting the right to vote? (투표권을 얻는 기준은 어떻게 되나요?)`,
    content: `Voting rights can be obtained when assets of 100 XOP or more are delegated to XO, and voting rights are given based on one day before the start of voting. (투표권은 100XOP 이상의 자산을 SO에게 위임했을 경우 얻을 수 있으며, 투표 시작 1일 전 기준 투표권 생성이 됩니다.)`,
    category: `vote`,
  },
  {
    id: 29,
    title: `Will the XOP used for voting disappear? (투표에 사용한 SOP는 소멸되나요?)`,
    content: `XOP do not disappear or are not burnt after used in vote. If you pertain more than 100 XOP delegated to each XO, voting rights will be given. (XOP는 투표에 사용되어도 사라지지 않으며, 각 SO에게 100XOP 이상의 위임량을 유지하면 다른 제안에도 투표권이 발급됩니다. )`,
    category: `vote`,
  },
  {
    id: 30,
    title: `What happens if the proposal doesn't accepted? (투표에 통과하지 못하면 어떻게 되나요?)`,
    content: `If the proposal is not approved by a minimum of 50% except abstention, it will be changed to Reject status and the deposit will be burned after the vote. (기권을 제외하고 제안이 50%의 찬성을 얻지 못하면 Reject 상태로 변경되고 제안 보증금은 투표가 끝난 후 소각됩니다.)`,
    category: `vote`,
  },
  {
    id: 31,
    title: `How long does the vote go alive? (투표 기간은 어떻게 되나요?)`,
    content: `For one week from the start of the voting. (투표 시작일로부터 일주일간 진행됩니다.)`,
    category: `vote`,
  },
  {
    id: 32,
    title: `Is there a disadvantage if I don't vote? (투표를 하지 않으면 불이익이 있나요?)`,
    content: `If you don’t vote, your voting rights are reflected as abstain. (투표권을 행사하지 않으면 기권 처리됩니다.)`,
    category: `vote`,
  },
  {
    id: 33,
    title: `Can I vote directly on the proposal? (제안에 직접 투표할 수 있나요?)`,
    content: `XOM sho delegated more than 100 XOP have the voting rights and can vote. Voted opinions are reflected according to XO group’s voting status. (100XOP 이상 위임한 XOM은 투표권을 부여받고 직접 투표할 수 있습니다. 투표된 의견은 XO 그룹별 투표 현황에 따라 전체 투표에 반영됩니다.)`,
    category: `vote`,
  },
  {
    id: 34,
    title: `How do I vote? (투표는 어떻게 진행하나요?)`,
    content: `XOM with voting rights vote Yes/No to the proposal.\nEach XO group which has reached 20% of quorum can submit opinion according to XOM vote. (투표권을 가진 SOM은 투표에 부쳐진 제안에 찬성/반대의 의견을 제출합니다.\nXO 그룹별로 SOM의 정족수가 20%인 경우 XOM의 투표 결과에 따른 찬성/반대 옵션을 일괄 반영합니다.)`,
    category: `vote`,
  },
  {
    id: 35,
    title: `Is the ranking reward immediately affected according to ranking change? (순위가 바뀌면 리워드도 즉시 적용되나요?)`,
    content: `The rewards are calculated daily at 1 am(UTC+9). The calculated rewards are given and become claimable at 3 pm(UTC+9) the next day. (매일 오전 1시 (UTC+9)에 Reward 계산을 진행하며, 사용자가 실제 확인 및 Claim 할 수 있는 시점은 익일 오후 3시 (UTC+9)입니다.)`,
    category: `reward`,
  },
  {
    id: 36,
    title: `Would delegation reward be given in XOP? (위임 보상도 XOP로 받나요?)`,
    content: `Delegation reward is given in TOKEN. Reward from invested project would be given in corresponding project token. (위임 보상은 TOKEN로 지급됩니다. 투자를 통한 보상은 투자를 진행한 프로젝트의 프로젝트 토큰으로 보상이 지급됩니다.)`,
    category: `reward`,
  },
  {
    id: 37,
    title: `Where can I check my reward? (리워드는 어디서 확인하나요?)`,
    content: `My reward will be displayed in My reward section on the XO detail page which you have delegated. You can bring the reward to wallet with the claim button. (내가 위임한 XO의 상세 페이지에 My reward로 나의 보상이 표시됩니다. claim 버튼으로 보상을 내 지갑으로 가져올 수 있습니다.)`,
    category: `reward`,
  },
  {
    id: 38,
    title: `How is the reward determined? (리워드는 어떻게 책정되나요?)`,
    content: `It is determined by considering additional reward for XO rankings in addition to the standard reward. (기본 보상 외에 XO 순위에 대한 추가보상을 고려하여 결정됩니다.)`,
    category: `reward`,
  },
  {
    id: 39,
    title: `The XYLO Wallet is automatically connected to the To Chain. Can’t I connect to another Wallet?`,
    content: `XYLO Wallet provides a function that automatically links once connected wallets for your convenience. If you reconnect to the bridge after a certain period of time or use the disconnection function at the top right, you can connect a new wallet. However, XYLO makes it a rule to provide one account per person, so please avoid using the bridge with another person’s account.`,
    category: `products`,
  },
  {
    id: 40,
    title: `What kind of fee is incurred when using the bridge?`,
    content: `Metamask 1st: Sign approval to allow smart contract to use tokens to complete the requested transaction, incurring a small Ethereum fee.\n\nMetamask 2nd: When contract is created, requests approval is processed and a small Ethereum fee is incurred.\n\nXYLO Wallet: Tax and bridge fee equal to 0.1% of the TOKEN you send will be incurred. (If you enter TOKEN Amount as Max, the amount corresponding to the fee will be excluded and entered.)`,
    category: `products`,
  },
  {
    id: 41,
    title: `I can’t see TOKEN in Metamask token list, how can I add TOKEN?`,
    content: `Add contract address at the add tokens in Metamask. Refer to the XYLO Docs: Use Bridge for the detailed information.\n\n0x9b9647431632af44be02ddd22477ed94d14aacaa\n\nIf an error occurs when adding contract address, please add token by referring to the image below in the coinmarketcap.`,
    category: `products`,
  },
  {
    id: 42,
    title: `I didn’t change the network with the Bridge and made a direct deposit to the XYLO Wallet. Can I find the TOKEN I accidentally deposited?`,
    content: `TOKEN by using the bridge when sending TOKEN of Ethereum network.\nDue to the nature of digital assets, recovery is not possible in case of incorrect deposit.\nIf you make a mistake, you can’t find TOKEN, so it is recommended to test conversion with a small amount of TOKEN first.\nAlso, even if the wallet address format of TOKEN and Ethereum is the same, they do not use the same blockchain network, so please check the network type.`,
    category: `products`,
  },
  {
    id: 43,
    title: `I chose to send the full amount, but the transmission failed. What's the cause?`,
    content: `Please enter the amount excluding the fee and try again.`,
    category: `products`,
  },
  {
    id: 44,
    title: `Where can I find the address of the To wallet?`,
    content: `The To wallet address is automatically entered in the Destination item. If you want to check it separately, you can check it through the linked Metamask or XYLO app.`,
    category: `products`,
  },
  {
    id: 45,
    title: `The window was accidentally turned off during the process. How do I check the progress?`,
    content: `You can check the history page for in-progress or completion history.`,
    category: `products`,
  },
  {
    id: 46,
    title: `I clicked the confirm transaction button, but the transmission failed. Will I still be able to get a refund?`,
    content: `If problems such as timeout or transmission failure occur in the To wallet, you can get a refund through the Refund button.`,
    category: `products`,
  },
  {
    id: 47,
    title: `Where do I approve the transaction?`,
    content: `If the Metamask is connected, it will proceed through the Metamask, and if the XYLO Wallet is connected, a button in the bridge web will be created separately.`,
    category: `products`,
  },
  {
    id: 48,
    title: `The bridge is still in transfer. Did transfer fail?`,
    content: `The transfer takes more than 5 minutes depending on the network environment. Please do not leave the page and wait. If the transfer fails, you can go to the History page and proceed with the refund.`,
    category: `products`,
  },
  {
    id: 49,
    title: `What are the From chain and To chain? What does it mean to have to connect both?`,
    content: `Bridge is a transport program for using assets on other networks in the XYLO network. The From chain is the Ethereum chain from which assets are transferred, and the To chain is the XYLO chain to which assets are transferred. Both chains need to be connected because they have to transfer assets between them.`,
    category: `products`,
  },
  {
    id: 50,
    title: `I need to connect my wallet to the bridge. Which wallet should I use?`,
    content: `Currently, Bridge supports metamasks. Please use the extended version of Chrome Metamask.`,
    category: `products`,
  },
  {
    id: 51,
    title: `Can't I use the bridge on mobile?`,
    content: `Currently, only web (PC) versions is supported. It is recommended to connect to the PC version of Chrome.`,
    category: `products`,
  },
  {
    id: 52,
    title: `Are all votes recorded on the blockchain? (모든 투표 내역은 블록체인에 기록이 되나요?)`,
    content: `All the transactions are recorded on the blockchain when voting starts, and the voting results are also recorded on the blockchain. However, to encourage the participation of XOM, the contents are not recorded on the blockchain during the vote, but only the final result is recorded through the administrator at the end of voting. (In order to record all voting details on the blockchain, voting transactions of members with voting rights need to pay transaction fees from their wallets, and only the results after voting are recorded) (투표 시작과 함께 블록체인에 기록되며, 투표 종료 결과 또한 블록체인에 기록됩니다. 단, XOM분들의 적극적인 참여 활성화를 위해 투표 진행 시에는 블록체인에 기록하지 않고 투표 종료 시 관리자를 통해 최종 결과 기록을 진행합니다. (블록체인에 모든 투표 내역을 기록하기 위해서는 투표권을 보유한 회원분들의 투표 트랜잭션을 본인의 월렛에서 트랜잭션 수수료 지불이 필요하여 투표 종료 시 결과만 기록합니다.))`,
    category: `products`,
  },
];
